### ISSUE TITLE
[BUG] Arclight 1.18.2 cannot boot with this mod.

### ISSUE THREAD

**Issue by MossCG** [auioc/hulsealib-mcmod#1]
### Description

I add this mod because of harmonicench, but on my arclight server, it crashed.
Maybe cause of mixin?

### Environment

Java 17
Windows 10
Arclight 1.18.2-1.08 
Forge 40.1.87
hulsealib-1.18.2-1.0.2

### Reproduction steps

1. add this mod to Arclight server
2. launch server
3. crash

### Expected behavior

fix

### Relevant logs

https://paste.ubuntu.com/p/mQYfpqvhTf/

**Comment by WakelessSloth56** [comment]
This is definitely caused by Mixin, but we will not deal with issues related to hybrid servers.
We welcome contributions, you can fix it and propose a pull request.
